%YAML 1.2
---
app_name: "MyApp"
version: "1.0"
database_url: "postgres://localhost:5432/myapp_db"
api_key: "default_api_key"
---
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "/var/log/myapp.log"
---
features:
  enable_feature_x: true
  enable_feature_y: false
