# This output is generated by calling `dir(__builtins__)` in Python. 
# The `__builtins__` is a module in Python that contains a collection of built-in functions, constants, and exceptions. 
# These are available globally throughout your Python code without the need to import them explicitly.

# The list includes:
# 1. Built-in exceptions: Errors like `ArithmeticError`, `IndexError`, `ZeroDivisionError`, etc., which are used to handle exceptions during runtime.
# 2. Built-in constants: Constants like `True`, `False`, `None`, etc., which are globally available.
# 3. Built-in functions: Functions like `print()`, `abs()`, `input()`, etc., which provide fundamental operations and are always accessible.

# Key items to note:
# - Exception handling: Classes such as `TypeError`, `ValueError`, and `KeyError` are critical for managing errors and controlling program flow during execution.
# - Functions: Functions like `len()`, `range()`, `map()`, and `filter()` allow you to perform common operations on data structures.
# - Constants: `True`, `False`, and `None` are boolean values and a special constant representing null or no value.

# Example: Using `print()` (which is a built-in function) to display text on the screen:
print("Hello, World!")  # Output: Hello, World!

# Using `dir(__builtins__)`, we can explore all these built-in names and their availability in Python.
print(dir(__builtins__))  # This lists all the names in the built-in namespace.
